apiVersion: apps/v1
kind: Deployment
metadata: { name: ipasnitch, labels: { app: ipasnitch } }
spec:
  replicas: 1
  selector: { matchLabels: { app: ipasnitch } }
  template:
    metadata: { labels: { app: ipasnitch } }
    spec:
      containers:
        - name: ipasnitch
          image: ghcr.io/cognis-digital/ipasnitch:latest
          ports: [{ containerPort: 8000 }]
          resources:
            requests: { cpu: "50m", memory: "64Mi" }
            limits: { cpu: "500m", memory: "256Mi" }
---
apiVersion: v1
kind: Service
metadata: { name: ipasnitch }
spec:
  selector: { app: ipasnitch }
  ports: [{ port: 80, targetPort: 8000 }]
